name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/docker-react npm run test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_ACCESS_SECRET }}
          application_name: 'Docker React Frontend'
          environment_name: DockerReactFrontend-env
          existing_bucket_name: elasticbeanstalk-us-east-2-122610517860
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
